name: Build
on:
  push:
    branches-ignore: [main]
    tags:
      # match semver tags, triggering modrinth releases
      # could be more restrictive, but this is a good start
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        java: [17, 18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ matrix.java == '17' }}
        with:
          name: libs
          path: build/libs/
