name: Lint
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        java: [17, 18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Validate Codebase
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
